checkmarble/marble-frontend

packages/app-builder/src/components/Filters/DateRangeFilter.tsx
One image to explain the whole fix:
> "24/01 -> 24/01" but I still want decisions from "24/01". 🤯
=> fix(DateRangeFilter): endDate is not included in the filter

packages/app-builder/src/components/Decisions/DecisionDetail.tsx, packages/app-builder/src/components/Decisions/DecisionsList.tsx
Add case status in front of case name in decision pages.
Bonus: improve link CSS
=> feat(Decisions): display case status next to case title

packages/app-builder/public/locales/en/common.json, packages/app-builder/src/components/Auth/SignInWithGoogle.tsx, packages/app-builder/src/components/Auth/SignInWithMicrosoft.tsx, packages/app-builder/src/models/toast-session.ts, packages/app-builder/src/services/auth/auth.client.ts
Improve error handling.
Errors are discovered using real Firebase service (emulator seems to be different in some circumstancies)
=> feat(sso): better error handling

packages/app-builder/src/services/auth/auth.client.ts
Miss from me: I thought it wasn't happenning on real Fireabse but seems it does
=> fix(auth): handle expired popup request

.firebaserc, firebase.json
Related to [this PR](https://github.com/checkmarble/marble-backend/pull/473)
=> chore(firebase): remove marble firebase projects

packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/_layout.tsx
Goal: improve future proof of the code
=> change the control flow for the activation of a scenario version

packages/app-builder/src/routes/_builder+/data.tsx
=> feat(data-table): change columns size

packages/app-builder/.env.example
New api key created for opensource
=> segment write key for open source users

packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/EditDataModelField.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/Modal.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandLabel.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandTooltip.tsx
=> fix(operand-label): improve display of long names

packages/app-builder/src/models/organization.ts, packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
With https://github.com/checkmarble/marble-backend/pull/490
=> drop unused database_name on organizations

packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/_layout.tsx
Hotfix to allow non admin to access scenario info
PS: if this is ok for you @Pascal-Delange we can cherry-pick this commit on the current released version
=> fix(deployment): check permission in loader

packages/ui-design-system/src/MenuWithCombobox/MenuWithCombobox.spec.tsx, packages/ui-design-system/src/MenuWithCombobox/MenuWithCombobox.stories.tsx, packages/ui-design-system/src/MenuWithCombobox/MenuWithCombobox.tsx, packages/ui-design-system/src/index.ts
First PR required for the refactoring of operand edit : introduce a new component Menu + Combobox (in order to drop the quick & dirty previous composition which was hacky).
PS: look at the storybook to see some example (behaviours: especially keyboard + focus managment + dismissing management)
=> feat(MenuWithCombobox): add MenuWithCombobox component

packages/app-builder/src/repositories/CaseRepository.ts, packages/app-builder/src/repositories/DecisionRepository.ts, packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
Adapt the frontend to the breaking change on DTOs
=> feat(marble-api): handle breaking changes in marble-api

packages/app-builder/public/locales/en/common.json, packages/app-builder/src/models/user.ts, packages/app-builder/src/routes/_builder+/_layout.tsx, packages/app-builder/src/utils/http/http-responses.ts
Gracefully reject marble admin user (and skip Sentry collection)
=> feat(marble-admin): gracefully reject marble admin user

packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx
Implement default global filter for rules list :
- default React Table implementation (= exact match)
- global (= on all columns)
- local (= no async call to server)
Bonus: reuse "highlight" matching text in purple comp (to improve UX)
=> feat(rules): add global local filter to rules list

packages/app-builder/src/components/Data/DataModelFlow.tsx, packages/app-builder/src/components/Data/LinkToSingleEdge.tsx, packages/app-builder/src/components/Data/TableDetails.tsx, packages/app-builder/src/components/Data/TableModelNode.tsx, packages/app-builder/src/components/Decisions/RulesDetail.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilder.tsx, packages/app-builder/src/models/data-model.ts, packages/app-builder/src/models/editable-ast-node.ts, packages/app-builder/src/repositories/DataModelRepository.ts, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/trigger.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/ressources+/data+/createField.tsx, packages/app-builder/src/routes/ressources+/data+/createLink.tsx, packages/app-builder/src/services/ast-node/options.tsx, packages/app-builder/src/services/data/data-model.tsx, packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
More work than expected (part of the changes are out of scope) :
- refactor a litle bit adapters
- change some modal implementation to fix some concurent `setState` bugs
=> refactor(data-model): use new DTOs in the data model

packages/app-builder/public/locales/en/data.json, packages/app-builder/src/routes/ressources+/data+/create-pivot.tsx
Handle specific 409 (=conflict) error when a pivot already exists.
=> feat(pivot): add 409 error handling to pivot creation

packages/app-builder/src/routes/_builder+/workflows+/_index.tsx
=> feat(workflows): add search highlighting to workflows table

packages/app-builder/src/components/Decisions/RulesDetail.tsx, packages/app-builder/src/models/scenario-iteration-rule.ts, packages/app-builder/src/models/scenario-iteration.ts, packages/app-builder/src/models/scenario-validation.ts, packages/app-builder/src/repositories/EditorRepository.ts, packages/app-builder/src/repositories/ScenarioIterationRuleRepository.ts, packages/app-builder/src/repositories/ScenarioRepository.ts, packages/app-builder/src/repositories/init.server.ts, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/rules+/create.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/rules+/delete.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/rules+/duplicate.tsx, packages/app-builder/src/services/auth/auth.server.ts, packages/app-builder/src/services/init.server.ts, packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
Small refacto to introduce `ScenarioIterationRuleRepository`
=> refactor(api): create repository for scenario iteration rules

packages/app-builder/public/locales/en/lists.json, packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
Distinguish empty list from empty search
=> feat(lists): handle empty search list

packages/app-builder/src/models/scenario-iteration-rule.ts, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/rules+/create.tsx, packages/app-builder/src/services/editor/current-scenario-iteration.tsx, packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
Changes required to use `rule_group` from API
=> feat(api): introduce rule_group field to scenario iteration rule

packages/marble-api/scripts/openapi.yaml, packages/marble-api/src/generated/marble-api.ts
Fix the wrong response declaration in the frontend while it's fresh
=> fix(api): wrong response payload

packages/ui-design-system/src/Combobox/Combobox.tsx
=> fix(rule-group): add missing hover color

packages/app-builder/src/models/transfer-alert.ts, packages/app-builder/src/models/transfer.ts, packages/app-builder/src/repositories/TransferAlertRepository.ts, packages/app-builder/src/repositories/init.server.ts, packages/app-builder/src/services/auth/auth.server.ts, packages/marble-api/openapis/transfercheck-api.yaml, packages/marble-api/src/generated/transfercheck-api.ts
Implement alert endpoints for transfercheck
=> feat(api): add alert endpoints for transfer check

packages/app-builder/src/components/Data/SelectedPivot.tsx, packages/app-builder/src/models/scenario-iteration.ts, packages/app-builder/src/services/editor/coerceToConstantEditableAstNode.ts
I updated all places where this func is used. 
I tested locally :
- draft issue
- select pivot highlight
- constant array coercicion
Everything works
=> fix(remeda): R.isDefined internal logic breaking change

packages/app-builder/src/services/validation/scenario-validation.ts
=> fix(validation): error in hasRuleError function

packages/app-builder/src/components/Scenario/Workflow/models/validation.ts
=> fix(workflow): issue when loading existing data

packages/app-builder/public/locales/en/common.json, packages/app-builder/src/components/Auth/ResetPassword.tsx, packages/app-builder/src/components/Auth/SendEmailVerification.tsx, packages/app-builder/src/components/Auth/SignUpWithEmailAndPassword.tsx, packages/app-builder/src/services/auth/auth.client.ts
Small improvment on error feedback for auth.
=> feat(firebase): improve errors feedback

packages/app-builder/src/models/license.ts
This reverts commit 739e9971b99847fe7ca6abd00bace1c2b0a7ddef.
=> Revert "hotfix(license): egg/chicken problem with webhooks"

packages/app-builder/src/entry.client.tsx, packages/app-builder/src/entry.server.tsx, packages/app-builder/src/services/segment/SegmentScript.tsx
=> chore(remix): update entry files

packages/app-builder/src/models/license.ts, packages/app-builder/src/models/rule-snooze.ts, packages/app-builder/src/models/user.ts, packages/app-builder/src/repositories/DecisionRepository.ts, packages/app-builder/src/repositories/LicenseRepository.ts, packages/app-builder/src/repositories/ScenarioRepository.ts, packages/app-builder/src/services/feature-access.server.ts, packages/app-builder/src/services/license.server.ts, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Classic new endpoint dedicated PR
=> feat(api): rule snoozing repository

packages/app-builder/public/locales/en/cases.json, packages/app-builder/src/components/Cases/CaseDecisions.tsx, packages/app-builder/src/models/duration.ts, packages/app-builder/src/models/rule-snooze.ts, packages/app-builder/src/repositories/DecisionRepository.ts, packages/app-builder/src/routes/_builder+/cases+/$caseId.tsx, packages/app-builder/src/routes/ressources+/cases+/add-rule-snooze.tsx
Handle rule snooze display :
- basic info when already setup
- CTA when available or info message if not
=> feat(rule-snoozing): add rule snooze conditionnal display

packages/app-builder/public/locales/en/scheduledExecution.json, packages/app-builder/src/components/ScheduledExecutions/ScheduledExecutionsList.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Completes https://github.com/checkmarble/marble-backend/pull/660
=> complete display of scheduled exec status

packages/app-builder/src/components/Decisions/Filters/DecisionFiltersContext.tsx, packages/app-builder/src/components/Decisions/Filters/FilterDetail/CaseInboxFilter.tsx, packages/app-builder/src/components/Decisions/Filters/FilterDetail/FilterDetail.tsx, packages/app-builder/src/components/Decisions/Filters/filters.ts, packages/app-builder/src/repositories/DecisionRepository.ts, packages/app-builder/src/routes/_builder+/decisions+/_index.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Use the same naming between backend and frontend (+ manual test of the feature)
=> refactor: use caseInbox instead of inbox in filter

packages/app-builder/public/locales/en/scenarios.json, packages/app-builder/src/models/organization.ts, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/trigger.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Linked to https://github.com/checkmarble/marble-backend/pull/680
=> feat(s3): deprecate s3 export

packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/activate.tsx
My turn to make a silly if condition mistake 🤦🏽
=> fix(activate-rule-snooze-issue): wrong condition for snooze

packages/app-builder/src/services/i18n/i18next.server.ts
Try to fix translation errors server side.
The difficutly is everything works locally 😢
=> fix(i18n): remove deprecated i18next server options

packages/app-builder/src/components/Scenario/Workflow/WorkflowProvider.tsx
Regression: it is probably linked to the `zustand` major update
=> fix(Workflow): infinite rendering loop

.github/workflows/build_and_deploy.yaml, packages/app-builder/src/components/Decisions/TriggerObjectDetail.tsx
Again... CI hell of debugging using error messages lost in 121633672567153 logs
=> fix(ci): last fixes for build and deploy workflow

packages/app-builder/src/routes/ressources+/data+/createField.tsx
See https://github.com/checkmarble/marble-backend/pull/727
=> validation: no name "id" on data model

packages/app-builder/src/locales/ar/scenarios.json, packages/app-builder/src/locales/en/scenarios.json, packages/app-builder/src/locales/fr/scenarios.json, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/decision.tsx
see https://checkmarble.slack.com/archives/C07R7KK70BX/p1730986963235699
=> add limits on threshold

packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx
=> fix: break long rules name

packages/app-builder/src/components/Auth/SignInWithGoogle.tsx, packages/app-builder/src/components/Auth/SignInWithMicrosoft.tsx, packages/app-builder/src/components/Callout.tsx, packages/app-builder/src/components/Cases/CaseHistory/CaseEvents.tsx, packages/app-builder/src/components/Cases/RuleSnoozes.tsx, packages/app-builder/src/components/Data/TableModelNode.tsx, packages/app-builder/src/components/Decisions/RulesExecutions/RulesExecutions.tsx, packages/app-builder/src/components/Decisions/ScoreOutcomeThresholds.tsx, packages/app-builder/src/components/Form/OldFormField.tsx, packages/app-builder/src/components/Navigation.tsx, packages/app-builder/src/components/Page.tsx, packages/app-builder/src/components/Paper.tsx, packages/app-builder/src/components/Ping/CornerPing.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditModal/FuzzyMatchComparatorEdit/FuzzyMatchComparatorEdit.tsx, packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandInfos.tsx, packages/app-builder/src/components/Scenario/Workflow/DetailPanel/DetailPanel.tsx, packages/app-builder/src/components/Scenario/Workflow/Nodes/shared.tsx, packages/app-builder/src/routes/_auth+/sign-up.tsx, packages/app-builder/src/routes/_builder+/analytics.tsx, packages/app-builder/src/routes/_builder+/api.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId._layout.tsx, packages/app-builder/src/routes/_builder+/decisions+/$decisionId.tsx, packages/app-builder/src/routes/_builder+/lists+/$listId.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/_layout.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/_builder+/workflows+/$scenarioId.tsx, packages/app-builder/src/routes/transfercheck+/alerts+/_.received.$alertId.tsx, packages/app-builder/src/routes/transfercheck+/alerts+/_.sent.$alertId.tsx, packages/app-builder/src/routes/transfercheck+/transfers+/$transferId.tsx, packages/ui-design-system/src/Select/Select.stories.tsx
=> refactor(css): remove left and right css classes

packages/app-builder/src/components/PaginationButtons.tsx, packages/app-builder/src/hooks/useCursorPaginatedFetcher.ts, packages/app-builder/src/hooks/useCursorPagination.ts, packages/app-builder/src/locales/ar/common.json, packages/app-builder/src/locales/en/common.json, packages/app-builder/src/locales/fr/common.json, packages/app-builder/src/models/inbox.ts, packages/app-builder/src/models/pagination.ts, packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx, packages/app-builder/src/routes/_builder+/decisions+/_index.tsx, packages/app-builder/src/routes/_builder+/settings+/inboxes.$inboxId.tsx, packages/app-builder/src/routes/ressources+/settings+/inboxes+/delete.tsx, packages/app-builder/src/routes/ressources+/settings+/inboxes+/inbox-users.delete.tsx, packages/app-builder/src/routes/ressources+/settings+/inboxes+/inbox-users.update.tsx, packages/app-builder/src/routes/ressources+/settings+/inboxes+/update.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Changing how pagination behave with no `totalCount` returned from the backend.
=> fix pagination timeouts

packages/app-builder/src/locales/ar/scenarios.json, packages/app-builder/src/locales/en/scenarios.json, packages/app-builder/src/locales/fr/scenarios.json, packages/app-builder/src/models/editable-operators.ts, packages/app-builder/src/services/validation/scenario-validation-error-messages.ts
- starts with: takes 2 operands of string type
- ends with: takes 2 operands of string type
Backend PR: https://github.com/checkmarble/marble-backend/pull/771
=> add starts_with and ends_with operators

.github/workflows/build_and_deploy.yaml, .github/workflows/main_push.yaml, .github/workflows/tags_push.yaml
Related to PR https://github.com/checkmarble/terraform/pull/49 which contains the main notes on the implementation (notion and code comments)
=> use workload identity federation

packages/app-builder/src/components/Cases/CaseDecisions.tsx
=> feat: open single decision detail by default

.eslintignore, packages/app-builder/src/components/Cases/CaseFiles.tsx, packages/app-builder/src/components/Cases/CasesList.tsx, packages/app-builder/src/components/Decisions/DecisionsList.tsx, packages/app-builder/src/components/Decisions/PivotDetail.tsx, packages/app-builder/src/components/TransferAlerts/AlertsList.tsx, packages/app-builder/src/components/Transfers/TransfersList.tsx, packages/app-builder/src/routes/_builder+/lists+/_index.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx, packages/app-builder/src/routes/_builder+/settings+/api-keys.tsx, packages/app-builder/src/routes/_builder+/settings+/inboxes.$inboxId.tsx, packages/app-builder/src/routes/_builder+/settings+/inboxes._index.tsx, packages/app-builder/src/routes/_builder+/settings+/tags.tsx, packages/app-builder/src/routes/_builder+/settings+/users.tsx, packages/app-builder/src/routes/_builder+/settings+/webhooks.tsx, packages/app-builder/src/routes/_builder+/settings+/webhooks_.$webhookId.tsx, packages/ui-design-system/src/Table/Table.tsx
In short: change the implemented solution to handle accessible clickable rows in tables.
**Before:** pseudo-content trick to stretch the <a> all over the row
**After:** use redundant click event, to programtically click the "visually hidden" row link
=> fix: table row link

packages/app-builder/src/hooks/useCursorPaginatedFetcher.ts
As the title said, useEffect was missing a dependency
=> fix: add missing dependency in useCursorPaginatedFetcher useEffect

packages/app-builder/src/locales/ar/scenarios.json, packages/app-builder/src/locales/fr/scenarios.json
The ar and fr translations where incorrect, compared to the en one and what the code expects.
=> fix wrong translations

packages/app-builder/src/components/Scenario/TestRun/TestRunNudge.tsx, packages/app-builder/src/components/Scenario/Workflow/WorkflowNudge.tsx, packages/app-builder/src/repositories/LicenseRepository.ts, packages/app-builder/src/repositories/init.server.ts, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/home.tsx
This PR update the homepage of the scenario.
As discussed precendently, we now have a section execution with each feature in it's oown block
=> style: updating the scenario homepage

packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/MainAstLine.tsx
Two things in this PR:
- Increase contrast of parentheses highlighting (not visible enough in previous version)
- Add brackets surrounding all the line if both direct children are main ast too
=> improve nesting visibility and extensibility

packages/app-builder/src/components/Cases/CasesList.tsx, packages/app-builder/src/components/Cases/Filters/CasesFiltersContext.tsx, packages/app-builder/src/components/Cases/Filters/FilterDetail/FilterDetail.tsx, packages/app-builder/src/components/Cases/Filters/FilterDetail/NameFilter.tsx, packages/app-builder/src/components/Cases/Filters/filters.ts, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/repositories/CaseRepository.ts, packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts
Add two new capabilities to the list of an inbox's case:
=> Add Ordering & Filtering on Case Manager

packages/app-builder/package.json, packages/app-builder/src/infra/firebase.ts, packages/app-builder/vite.config.ts, pnpm-lock.yaml
With the activation of single fetch api of Remix, tracking how data flow on the application was becoming arduous.
=> chore: add remix dev tools

packages/app-builder/src/components/Files/AddYourFirstFile.tsx, packages/app-builder/src/components/Files/FilesList.tsx, packages/app-builder/src/models/sanction-check.ts, packages/app-builder/src/repositories/SanctionCheckRepository.ts, packages/app-builder/src/routes/_builder+/cases+/$caseId._layout.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId.files.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId_.sanctions.$decisionId+/_layout.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId_.sanctions.$decisionId+/files.tsx, packages/app-builder/src/routes/ressources+/files+/upload-file.tsx, packages/app-builder/src/services/DownloadFilesService.ts, packages/app-builder/src/utils/files.ts, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/src/generated/marblecore-api.ts, packages/ui-design-system/src/Table/Table.tsx
- Add possibility to upload, list and download files for sanction check
- Refactor all files upload/listing/download components to be the same between cases and sanction check
=> feat: add uplad/listing/download sanction check files

packages/app-builder/package.json, packages/app-builder/src/components/Cases/CaseDecisions.tsx, packages/app-builder/src/components/Decisions/ReviewStatusTag.tsx, packages/app-builder/src/components/Form/FormSelect.tsx, packages/app-builder/src/components/Sanctions/MatchCard.tsx, packages/app-builder/src/components/Sanctions/MatchResult.tsx, packages/app-builder/src/components/Sanctions/RefineSearchModal.tsx, packages/app-builder/src/components/Sanctions/SanctionReview.tsx, packages/app-builder/src/components/Sanctions/SanctionStatusTag.tsx, packages/app-builder/src/constants/sanction-check-entity.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/ar/sanctions.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/en/sanctions.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/locales/fr/sanctions.json, packages/app-builder/src/models/sanction-check.ts, packages/app-builder/src/routes/ressources+/cases+/review-decision.tsx, packages/app-builder/src/routes/ressources+/sanction-check+/refine.tsx, packages/app-builder/src/routes/ressources+/sanction-check+/search.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/tailwind-preset/src/tailwind.config.ts, packages/ui-design-system/src/Modal/Modal.tsx, pnpm-lock.yaml
make refine modal buttons sticky with shadow
get rid of parseWithZod in sanction check actions
update refine modal & collapsible
disable approve decision if sanction in review
fix: DisplayNames don't like some regions format
fix: refine on correct entities
=> feat: sanction misc changes

packages/app-builder/src/entry.server.tsx, packages/app-builder/src/locales/ar/scenarios.json, packages/app-builder/src/locales/en/scenarios.json, packages/app-builder/src/locales/fr/scenarios.json, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/home.tsx
=> Add 'Archived' button to test-run + increase timeout

packages/app-builder/src/components/Cases/RuleSnoozes.tsx, packages/app-builder/src/components/Nudge.tsx, packages/app-builder/src/components/Scenario/TestRun/TestRunNudge.tsx, packages/app-builder/src/components/Scenario/Workflow/WorkflowNudge.tsx, packages/app-builder/src/locales/ar/common.json, packages/app-builder/src/locales/en/common.json, packages/app-builder/src/locales/fr/common.json, packages/app-builder/src/models/license.ts, packages/app-builder/src/repositories/LicenseRepository.ts, packages/app-builder/src/repositories/init.server.ts, packages/app-builder/src/routes/_builder+/_layout.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/home.tsx, packages/app-builder/src/routes/ressources+/settings+/webhooks+/create.tsx, packages/app-builder/src/routes/ressources+/settings+/webhooks+/update.tsx, packages/app-builder/src/services/feature-access.ts, packages/app-builder/src/services/init.server.ts, packages/marble-api/openapis/license-api.yaml, packages/marble-api/src/generated/license-api.ts
- Adding new style for missing configuration
- Update Feature acess with new missing configuration
Related Backend PR https://github.com/checkmarble/marble-backend/pull/821
=> Handle missing configuration

packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/sanction.tsx, packages/ui-design-system/src/Modal/Modal.tsx
- Wrong z-index on modal
- Rule group optional on Rule & Sanction Page
=> Wrong z-index on modal & optional rule group for rule & sanction form

packages/app-builder/src/models/license.ts, packages/app-builder/src/routes/_builder+/settings+/_layout.tsx, packages/app-builder/src/routes/_builder+/settings+/scenarios.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/sanctions+/create.tsx, packages/app-builder/src/services/feature-access.ts
- Disable webhook entry in settings & add nudge if missing configuration
- Remove sanction setting in settings tab if `restricted`
- Disable "Add new Sanction Check" if missing configuration & adding nudge
=> Finalizing missing configuration

packages/app-builder/.env.example, packages/app-builder/src/entry.client.tsx, packages/app-builder/src/repositories/AuthenticationRepository.ts, packages/app-builder/src/services/auth/auth.client.ts, packages/app-builder/src/services/auth/auth.server.ts, packages/app-builder/src/services/init.server.ts, packages/app-builder/src/utils/environment.ts
Prerequisite for the PR https://github.com/checkmarble/marble/pull/80, see link
=> rename _DOMAIN to _URL in env vars for back-front homogeneity and more explicit name

packages/app-builder/src/models/user.ts
Fix that goes with https://github.com/checkmarble/marble-backend/pull/903
=> small fix on permission names for custom lists management

packages/app-builder/src/components/Cases/CasesList.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/ressources+/cases+/edit-status.tsx
=> Little improvement to Case

packages/app-builder/src/components/Scenario/Sanction/FieldNode.tsx
Fix wrong condition in FieldNode which was preventing the node to be changed
=> fix FieldNode wrong condition onSave

packages/app-builder/src/components/Auth/SignInWithEmailAndPassword.tsx, packages/app-builder/src/components/Auth/SignUpWithEmailAndPassword.tsx, packages/app-builder/src/components/Form/Tanstack/FormInput.tsx, packages/app-builder/src/components/Form/Tanstack/FormTextArea.tsx, packages/app-builder/src/components/Scenario/Sanction/FieldRuleGroup.tsx, packages/app-builder/src/components/Scenario/TestRun/Filters/FilterDetail/StatusesFilter.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx, packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/sanction.tsx, packages/app-builder/src/routes/ressources+/cases+/add-rule-snooze.tsx, packages/app-builder/src/routes/ressources+/cases+/add-to-case.tsx, packages/app-builder/src/routes/ressources+/cases+/review-sanction-match.tsx, packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/sanctions+/create.tsx, packages/app-builder/src/routes/ressources+/scenarios+/create.tsx, packages/ui-design-system/src/Checkbox/Checkbox.tsx
=> Forms Update - Fixing some issues raised by QA

packages/app-builder/src/routes/ressources+/cases+/add-comment.tsx
Reset add comment form after submit
=> Reset Add comment form after submit

packages/app-builder/src/components/Tags/ColorPreview.tsx, packages/app-builder/src/components/Tags/ColorSelect.tsx, packages/app-builder/src/models/tags.ts, packages/app-builder/src/routes/_builder+/_layout.tsx, packages/app-builder/src/routes/_builder+/settings+/tags.tsx, packages/app-builder/src/routes/ressources+/settings+/tags+/create.tsx, packages/app-builder/src/routes/ressources+/settings+/tags+/update.tsx, pnpm-lock.yaml
For more info about the issue from radix-ui, here is an [interesting link](https://github.com/shadcn-ui/ui/issues/1668)
For more context:
- When we use a select inside a dialog on Firefox & Safari, we get a memory leak
- So we decided to use `MenuCommand` component from Marble in order to avoid this memory leak
- The issue about the select & the dialog is still pending on shadcn & radix side
=> Fix Memory Leak on Firefox

packages/app-builder/src/locales/ar/auth.json, packages/app-builder/src/locales/en/auth.json, packages/app-builder/src/locales/fr/auth.json, packages/app-builder/src/routes/_auth+/sign-up.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/openapis/marblecore-api/signup-status.yml, packages/marble-api/src/generated/marblecore-api.ts
Display a warning message on the signup page when there is no organization or user in the database.
The link brings to the [first connection documentation page](https://github.com/checkmarble/marble/blob/main/installation/first_connection.md)
=> feat(signup): Warn the user if db is not seeded

packages/app-builder/src/locales/ar/lists.json, packages/app-builder/src/locales/en/lists.json, packages/app-builder/src/locales/fr/lists.json, packages/app-builder/src/models/custom-list.ts, packages/app-builder/src/routes/_builder+/lists+/$listId.tsx, packages/app-builder/src/routes/_builder+/lists+/_index.tsx, packages/app-builder/src/routes/ressources+/lists+/value_create.tsx, packages/marble-api/openapis/marblecore-api/custom-lists.yml, packages/marble-api/src/generated/marblecore-api.ts
Display the values count on the custom lists page.
=> feat(custom-lists): Display values count on lists page

packages/app-builder/src/components/Cases/CaseAssignedTo.tsx, packages/app-builder/src/components/Cases/CasesList.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json
Add a Assigned column on cases list.
=> feat(case-manager): display assignee to the cases list

packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/ressources+/cases+/edit-assignee.tsx
- Add i18n on button
- Fix english copy typo
- submit change on click
=> fix(inbox): assign to me button

packages/app-builder/src/locales/ar/data.json, packages/app-builder/src/locales/en/data.json, packages/app-builder/src/locales/fr/data.json, packages/app-builder/src/routes/ressources+/data+/$tableId.createNavigationOption.tsx, packages/ui-design-system/src/MenuCommand/MenuCommand.tsx
- Add wording for explanation
- Remove arrow on disabled select buttons
=> fix: fix navigation option creation modal UI

packages/app-builder/src/components/Auth/SignInWithEmailAndPassword.tsx, packages/app-builder/src/services/auth/auth.client.ts
- Remove the user not found error
- Fix the form error handling
=> fix(sign-in): display error messages

packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/DataModelExplorer/ClientObjectDataList.tsx, packages/app-builder/src/components/DataModelExplorer/DataTableRender.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/models/data-model.ts, packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx, packages/app-builder/src/routes/_builder+/settings+/data-display.tsx
- Display related data dans le drawer du case manager
- table options management in data model for client data display
=> fix: fix related object display

packages/app-builder/src/entry.server.tsx
Quick PR to go with https://github.com/checkmarble/marble-backend/pull/982
=> silence sentry remix errors for "404-405"

packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/_builder+/cases+/_index.tsx, packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx, packages/app-builder/src/routes/_builder+/cases+/inboxes._layout.tsx
- Renames “All my cases” to “My Inbox”.
- Moves it to the top of the navigation list.
- Applies a more button-like style to make it stand out.
=> feat(cases-manager): Rename and move my inbox

packages/app-builder/src/components/Cases/CasesList.tsx
Reuses the same date display logic as in the case events list.
If the date is older than yesterday, the full date is shown.
=> feat(cases-inbox): Enhance the date display in list

packages/app-builder/src/components/CaseManager/Drawer/Drawer.tsx, packages/app-builder/src/components/CaseManager/Drawer/DrawerIcon.tsx
Made the padding of the drawer button be part of the buttons
=> fix: drawer buttons clickable size

packages/app-builder/src/routes/_auth+/sign-in.tsx, packages/app-builder/src/routes/_auth+/sign-up.tsx
Fix regression to gracefully handle Marble API downtime on the sign-in and sign-up pages.
=> fix(sign-in): Improve backend error handling

packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json
- Discriminate pivot objet on more than pivot values
- Add message to configure pivot when empty
=> fix: add empty state for pivot panel & discriminate pivots

packages/app-builder/src/components/DataModelExplorer/DataTableRender.tsx
- Order fields in data explorer column filter dropdown
=> fix field order in filter field dropdown of data exploration

packages/app-builder/src/components/CaseManager/SnoozePanel/SnoozePanel.tsx, packages/app-builder/src/components/DataModelExplorer/ClientObjectDataList.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx
=> QA - Update Snooze Panel 

packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/DataModelExplorer/ClientObjectDataList.tsx, packages/app-builder/src/components/DataModelExplorer/DataTableRender.tsx
- It adds the table name of the pivot on the right of the information panel
- Manage if the pivot has been ingested (no view more/less button if not ingested)
=> fix: manage pivot object correctly

packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/ressources+/cases+/escalate-case.tsx
- Add a `text-wrap: balance` to the callout.
- Add line break in the translations.
=> feat(case-manager): improve escalation callout readability

packages/app-builder/src/routes/ressources+/cases+/add-comment.tsx
- Make the event note mandatory.
- Validate the form on mount and on change.
=> fix(case-manager): Prevent submit flooding

packages/app-builder/src/root.tsx, packages/app-builder/src/utils/environment.ts
Error on my side in the previous PR, sorry.
=> fix error on disableSegment env var parsing

packages/app-builder/src/components/CaseManager/DecisionPanel/DecisionPanel.tsx, packages/app-builder/src/components/CaseManager/Drawer/Drawer.tsx, packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanel.tsx, packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/Cases/CaseDetails.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx, packages/tailwind-preset/src/tailwind.config.ts
Improve scroll behaviour on case manager page (independent scrollong main and panel, sticky sentinels and visual cues)
=> fix(case manager): rework right panel/drawer css

packages/app-builder/src/routes/_builder+/cases+/inboxes._layout.tsx, packages/app-builder/src/routes/_builder+/settings+/_layout.tsx, packages/app-builder/src/services/feature-access.ts
=> fix(inbox list): remove create inbox button when there's at least 1 inbox and show settings button MAR-946

packages/app-builder/src/components/CaseManager/SnoozePanel/SnoozePanel.tsx, packages/app-builder/src/components/Cases/CaseAlerts.tsx, packages/app-builder/src/components/Nudge.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx
[Linear issue](https://linear.app/marble-eu/issue/MAR-971/several-improvements-on-snooze-rule-functionality)
=> Minor improvements to Snooze Panel + Nudge

packages/app-builder/src/components/CaseManager/DecisionPanel/DecisionPanel.tsx, packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/CopyToClipboardButton.tsx
I decided to add the decision ID to the panel into this PR
=> Add time to list of previous case & Id to Decision Panel

packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/CaseManager/SnoozePanel/SnoozePanel.tsx, packages/app-builder/src/components/Cases/CaseDetails.tsx, packages/app-builder/src/components/Cases/CaseEvents.tsx, packages/app-builder/src/components/DataModelExplorer/ClientObjectDataList.tsx, packages/app-builder/src/components/FormatData.tsx, packages/app-builder/src/components/Nudge.tsx
=> refactor: Some Improvements & Correction

packages/app-builder/src/routes/ressources+/data+/create-annotation.tsx
Fixes tag selection success check
refs: MAR-1068
=> fix: correct the tag selection

packages/app-builder/src/routes/ressources+/cases+/close-case.tsx
Goes with https://github.com/checkmarble/marble-backend/pull/1052
=> mini-fix: do not pass reject silently on an action that makes 2 calls to the backend

packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/ressources+/cases+/review-decision.tsx
=> [Multiple Screening] QA returns

packages/app-builder/src/locales/ar/data.json, packages/app-builder/src/locales/fr/data.json
`<Code>` components had typo in French and Arabic translations.
=> fix(datamodel): typo in 18n tags

packages/app-builder/src/components/Scenario/Sanction/FieldSkipIfUnder.tsx
@ChibiBlasphem I'd appreciate a second opinion on my css here
=> wip: fix text row size

Dockerfile
=> fix segment env var setup in dockerfile

packages/app-builder/src/models/app-config.ts, packages/app-builder/src/routes/_auth+/_layout.tsx, packages/app-builder/src/routes/_auth+/sign-in-email.tsx, packages/app-builder/src/routes/_auth+/sign-in.tsx, packages/marble-api/openapis/marblecore-api/misc.yml, packages/marble-api/src/generated/marblecore-api.ts
- Make main illustration bigger to avoid creating a empty space on the left part of the page
- Use IsManagedMarble app config to display or not the demo button
=> feat(signin): improvments on signin flow redesign

packages/app-builder/src/components/Sanctions/SanctionReview.tsx
Backend PR: https://github.com/checkmarble/marble-backend/pull/1114
=> feat(screenings): make possible to no_hit and whitelist matches on partial screenings MAR-1174

packages/app-builder/src/routes/ressources+/cases+/add-comment.tsx, packages/app-builder/src/routes/ressources+/cases+/snooze-case.tsx
- Change the Unsnooze button to directly perform the unsnooze action instead of displaying the snooze case menu.
- Prevent users from selecting a past date in the custom date selector when snoozing a case.
- ~~Automatically unsnooze a case immediately after a comment is posted if the case was snoozed.~~
Refs: MAR-1201
=> fix(case-manager): unsnooze button

package.json, packages/app-builder/package.json, pnpm-lock.yaml
- Bump zod v4.1.4 (app-builder package)
- Bump Biome v2.2.2 (root)
=> chore: Bump zod v4.1.4 + Biome v2.2.2

packages/app-builder/src/components/Sanctions/ReviewScreeningMatch.tsx
- Linked confirm modal save button to review form
=> fix(screening): fix nothing happening when confirming a hit

packages/app-builder/src/components/Cases/CaseDetails.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json
=> feat(case-manager): display date until a case is snoozed

packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx, packages/app-builder/src/components/CaseManager/SnoozePanel/SnoozePanel.tsx, packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx
Open question on whether it's ok to export the PivotObjectDetails like I did, or if it should be moved somewhere else
=> fix on rule snooze & improvement

packages/app-builder/src/components/Cases/AddComment.tsx
Page loader was not revalidated after posting a comment.
Ref: MAR-1218
=> fix: typo in function call

packages/app-builder/src/components/Nudge.tsx
=> fix: add pointer-event auto to Nudge HoverCard

.github/workflows/build_and_deploy.yaml
=> chore(build): update sentry organisation

bun.lock, package.json, packages/app-builder/package.json, packages/app-builder/src/models/analytics/decisions-outcomes-perday.ts, packages/app-builder/src/models/analytics/index.ts, packages/app-builder/src/models/analytics/legacy-analytics.ts, packages/app-builder/src/repositories/AnalyticsRepository.ts, packages/app-builder/src/routes/_builder+/analytics.tsx, packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/openapis/marblecore-api/_schemas.yml, packages/marble-api/openapis/marblecore-api/analytics.yml, packages/marble-api/openapis/marblecore-api/misc.yml, packages/marble-api/src/generated/marblecore-api.ts
- Install new graph library and bar charts module.
- Create new endpoint openApi manifest.
- Mark exisiting endpoints references, repository functions and models as legacy ones.
- Prepare new models.
Refs: MAR-1252
=> feat(in-app-analytics): Prepare new analytics page

packages/app-builder/src/components/InputWithButton.tsx, packages/app-builder/src/locales/ar/cases.json, packages/app-builder/src/locales/en/cases.json, packages/app-builder/src/locales/fr/cases.json, packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
Add new input to access a case with ID.
=> feat: search case by id MAR-1248

packages/marble-api/openapis/marblecore-api.yaml, packages/marble-api/openapis/marblecore-api/_schemas.yml, packages/marble-api/openapis/marblecore-api/cases.yml, packages/marble-api/src/generated/marblecore-api.ts
=> OpenAPI spec for case mass update.
