checkmarble/marble-frontend

- packages/app-builder/public/locales/en/common.json
- packages/app-builder/public/locales/en/decisions.json
- packages/app-builder/public/locales/en/scenarios.json
- packages/app-builder/src/components/Decisions/Filters/DecisionFiltersContext.tsx
- packages/app-builder/src/components/Decisions/Filters/FilterDetail/FilterDetail.tsx
- packages/app-builder/src/components/Decisions/Filters/FilterDetail/HasCaseFilter.tsx
- packages/app-builder/src/components/Decisions/Filters/filters.ts
- packages/app-builder/src/components/Decisions/decisions-i18n.ts
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditorSearchResults.tsx
- packages/app-builder/src/components/Scenario/scenario-i18n.ts
- packages/app-builder/src/repositories/DecisionRepository.ts
- packages/app-builder/src/routes/_builder+/decisions+/_index.tsx
- packages/app-builder/src/services/editor/coerceToConstantsLabelledAst.ts
- packages/marble-api/scripts/openapi.yaml
- packages/marble-api/src/generated/marble-api.ts
As discussed, I implemented this by allowing to filter by the different cases "is attached to a case" and "is not attached to a case".
Maybe not totally ideal compared to just allowing one of those two options (assuming only one of them really makes sense from a product perspective) where we could have worked more easily with a toggle in the filter, but let's keep it like this for now.
The back-end API is a change compared to the current implementation, cf https://github.com/checkmarble/marble-backend/pull/462
> feat: add filter on has case/has no case on decisions page

- packages/app-builder/public/locales/en/scheduledExecution.json
- packages/app-builder/src/components/Decisions/DecisionsList.tsx
- packages/app-builder/src/components/Scenario/Iteration/VersionSelect.tsx
- packages/app-builder/src/components/ScheduledExecutions/ScheduledExecutionDetails.tsx
- packages/app-builder/src/components/ScheduledExecutions/ScheduledExecutionsList.tsx
- packages/app-builder/src/routes/_builder+/data.tsx
- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/_layout.tsx
- packages/app-builder/src/routes/_builder+/settings+/inboxes.$inboxId.tsx
- packages/app-builder/src/routes/_builder+/settings+/tags.tsx
- packages/app-builder/src/routes/_builder+/settings+/users.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/create_draft.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/deployment.tsx
- packages/ui-design-system/src/Table/Table.tsx
Small UI refactor to enable horizontal scrollability on tables :
- add a horizontal scroll indicator (always displayed when scrollable)
- start to scroll horizontally when the config pixel size is reached
Bonus: revamp some configs to set enlarge sizes (previously, the table was so shrinked, certain tables where unreadable)
Concretelly, here is an example :
**Before** actions on the right are unreachable (no scrolling)
**After** actions are accessible by scrollin, table is less shrinked
> refactor(table): horizontal scrollable tables

- packages/app-builder/src/repositories/ScenarioRepository.ts
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/trigger.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/validate-with-given-trigger-or-rule.tsx
- packages/marble-api/scripts/openapi.yaml
- packages/marble-api/src/generated/marble-api.ts
In this PR :
- remove the GET validation endpoint from the API
- refactor validation related repository + `validate-with-given-trigger-or-rule`: the main idea is to expose higher level resources to the frontend
- get trigger specific validation
- get rule specific validation
In the future, we may want to only validate a portion of the ast or equivalent, this interface makes it easier to change (and understand what's really going on)
> refactor(validation): use a single endpoint for validation

- packages/app-builder/src/infra/firebase.ts
- packages/app-builder/src/repositories/AuthenticationRepository.ts
This is an attempt to fix the "double login" issue (first one result in an error, second one works).
From time to time, users experiment a "first login attempt failure". 
It seems to be related to a Firebase error due to a lack of permission on the token. It may be due to the current `logout` process which clear the user session but not the firebase client side data.
In order to ensure a Firebase login won't reuse local data, we enforce a `logout` before each sign in/sign up attempt.
> fix(firebase): add logout method to firebase service

- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/decision.tsx
Fix the bug on decision page.
Regression may happen during last pkg update (there was an issue on `disabled` form)
> fix(DecisionForm): unexpected errors when disabled

- packages/app-builder/src/routes/_builder+/_layout.tsx
Idea of the day: simple to add and usefull (especially when you're not admin and can't access org settings)
> feat(user): add role info to user profile

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/EditFilters.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/Modal.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/TimeAddEdit/Modal.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/RootAstBuilderNode/RootAnd.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/RootAstBuilderNode/RootOrWithAnd.tsx
- packages/app-builder/src/components/Scenario/ScenarioValidationError.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/decision.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/trigger.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx
Improve `EvaluationErrors` handling: there was a lot of specific rendering for that, especially inside aggregation modal
- expose a better abstraction
- handle errors as an array to give consistency accross screens to display errors
- the first refactor I did was too specific
- fix a lot of layering issues (especially between `view` and `edit` mode): this is UI only
> refactor(EvaluationErrors): improve error messages UI

- packages/ui-design-system/src/ScrollArea/ScrollArea.tsx
Fix a stacking issue (due to `z-index` that display scroll thumbs above modals (like in the capture)
> fix(ScrollArea): fix stacking issue

- packages/app-builder/src/components/Cases/CaseEvents.tsx
Bug spotted during the last demo: the `'comment_added'` case has been accidentally removed
> fix(CaseEvents): accidentally removed comment_added case

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandInfos.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operator.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/TwoOperandsLine.tsx
- packages/app-builder/src/models/ast-node.ts
- packages/app-builder/src/models/editable-ast-node.ts
- packages/app-builder/src/models/editable-operators.ts
- packages/app-builder/src/services/editor/ast-editor.ts
In this PR :
- create all models required to handle new fuzzy match operators
- implement "sumarry display" logic
- editability is out of scope
Caveat: currently, "editability" and specific "display" logic are heavilly compled, so it's not easilly possible to implement a "non editable" specific node with a custom "display" logic, so in "two line operand" specific case, you can display a fuzzy match node, and edit it (so you can remove it without the possibility to re-add it since this is not fully editable yet).
Still we are in a feature branch and this is temporary.
Bellow, some example on how this is rendered in the UI using different possibility :
- in left OR operator:
- single comparison
- multiple possibility (constants, with database access, with list...)
- non editable (this is a …
> feat(models): add fuzzy match functions

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/Operand.tsx
- packages/app-builder/src/services/ast-node/return-value.tsx
Improve return values formatting :
- boolean: use localised values (like in the editor)
- number: use two fractionnal digit max precision
> feat(return-values): better number formatting

- packages/app-builder/public/locales/en/upload.json
- packages/app-builder/src/routes/_builder+/upload+/$objectType.tsx
Use a specific error message when a Timeout occure in the frontend for data upload
> feat(upload): handle 408 on data upload page

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilder.tsx
We finally hit the issue with "global modal context provider" pattern : Aggregation and FuzzyMatch Contexts require to be a child of one another... impossible theoritically.
I hack by duplicating one context, since we do not allow to open "Aggregation" modal on top of "Fuzzy" one, we can't reach another "missing provider" issue.
The long term solution would be to create modals "locally" directly where it's needed (here, inside the edit operand dropdown), meaning we create a local context for each menu option requiring it (no more shared global context)
> hotfix(fuzzy-match): missing context provider issue

- packages/app-builder/src/services/editor/coerceToConstantEditableAstNode.spec.ts
- packages/app-builder/src/services/editor/coerceToConstantEditableAstNode.ts
Fix this issue :
NB: the problem only occured for single letter items, see exemple
> fix(coerceToConstant): coercion of single letter string constant

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/EditDataModelField.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/TimeAddEdit/Modal.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/TimeAddEdit/TimestampField.tsx
I tried to go further in the fix by using the `Operand` shared component as I did inside the "fuzzy match" edit modal but I faced the same issue related to shared modal context...
So for now, those changes fix the bug, and I created Linear tasks to tackle the long term refactor accordingly in the future.
> fix(TimeAddEdit): dropdown should extend outside the modal

- packages/app-builder/src/services/data/pivot.tsx
Opinionated way to remove possible "duplicate" pivot options (cf Linear issue for an example).
As a reminder, a pivot field is identified by the field name while an "equivalent" link field by the link name. If they both have the same value, this may introduce confusion (like in the example from Linear issue).
> feat(pivot): filter out field pivot options used in link options

- packages/app-builder/src/root.tsx
Small improvment to finish the day: revalidate root loader (the one that handle the CSRF) on the `/sign-in` page
> feat(sign-in): refresh csrf on window focus

- packages/app-builder/src/components/CopyToClipboardButton.tsx
- packages/app-builder/src/routes/_builder+/analytics.tsx
- packages/app-builder/src/routes/_builder+/api.tsx
- packages/app-builder/src/routes/_builder+/cases+/$caseId.tsx
- packages/app-builder/src/routes/_builder+/decisions+/$decisionId.tsx
- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx
- packages/app-builder/src/routes/_builder+/settings+/api-keys.tsx
- packages/app-builder/src/routes/_builder+/workflows+/$scenarioId.tsx
- packages/app-builder/src/routes/transfercheck+/transfers+/$transferId.tsx
Small UI update to better handle long titles.
An example :
Before:
After:
> refactor(header): better handling of long titles

- packages/app-builder/src/services/segment/getPageviewNameAndProps.ts
- packages/app-builder/src/services/segment/index.tsx
Refactor analytics :
- use zod schema to ensure consistant data collection (and re-use already defined custom schema)
- use `safeParse` to only collect valid data (and silently ignore parsing failure)
NB: this is motivated by [this](https://checkmarble.sentry.io/issues/4573421844/?environment=production&project=4506060678037504&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0&utc=true) recent Sentry unhandled error
> fix(segment): use zod schema with safeParse

- packages/app-builder/public/locales/en/navigation.json
- packages/app-builder/public/locales/en/transfercheck.json
- packages/app-builder/src/components/Cases/Filters/CasesFiltersContext.tsx
- packages/app-builder/src/components/TransferAlerts/AlertStatus.tsx
- packages/app-builder/src/components/TransferAlerts/AlertsList.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/AlertsFiltersBar.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/AlertsFiltersContext.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/AlertsFiltersMenu.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/FilterDetail/AlertsDateRangeFilter.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/FilterDetail/FilterDetail.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/FilterDetail/MessageFilter.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/FilterDetail/StatusesFilter.tsx
- packages/app-builder/src/components/TransferAlerts/Filters/FilterDetail/index.ts
- packages/app-builder/src/components/TransferAlerts/Filters/filters.ts
- packages/app-builder/src/components/TransferAlerts/Filters/index.ts
- packages/app-builder/src/models/cases.ts
- packages/app-builder/src/models/transfer-alert.ts
- packages/app-builder/src/routes/ressources+/cases+/edit-status.tsx
- packages/app-builder/src/routes/transfercheck+/_layout.tsx
- packages/app-builder/src/routes/transfercheck+/alerts+/inboxes._index.tsx
- packages/app-builder/src/routes/transfercheck+/alerts+/inboxes._layout.tsx
- packages/app-builder/src/routes/transfercheck+/alerts+/inboxes.received.tsx
- packages/app-builder/src/routes/transfercheck+/alerts+/inboxes.sent.tsx
- packages/app-builder/src/services/transfercheck/alerts/alerts.tsx
- packages/app-builder/src/utils/routes/routes.ts
- packages/app-builder/src/utils/routes/types.ts
- packages/app-builder/src/utils/schema/filterSchema.ts
- packages/app-builder/src/utils/table-filter-fn.ts
Huge PR to introduce :
- split between sent and received alerts
- implement filters on the alerts list
- full text search on message
- status filter
- created_at filter (= date range)
NB: alert detail split will come in a future PR and proper alert status also (currently it's the old `read`, `unread`, `archived`)
> refactor(alerts): split sent and received alerts and add filters

- packages/app-builder/src/models/transfer-alert.ts
- packages/app-builder/src/routes/transfercheck+/ressources+/alert.create.tsx
- packages/app-builder/src/routes/transfercheck+/ressources+/alert.update.tsx
Small changes :
- better schema (only move optionnal + max length, based on what we discussed I didn't implemented a "smart" schema on IBAN or Transfer end2end id requirement)
- consistent ordering based on the same order used in the AlertData component
- small fixes on the adapters to allow the possibility to remove an optionnal field (with the current optionnal implem on the API, a missing field is equivalent to no PATCH changes, so we need to explicitly inform of removed fields)
NB: in fine, in a lot of places, I tends to inject "nullable values" for all missing fields to enforce the possibility to remove a field. Finally, I do more or less a PUT every time... not a big deal but if you have a better idea on how do deal with PATCH +  "delete some fileds" tell me your idea
> refactor(transfer-alert): improve validation

- packages/app-builder/src/components/Auth/SignInWithEmailAndPassword.tsx
- packages/app-builder/src/components/Auth/SignInWithGoogle.tsx
- packages/app-builder/src/components/Auth/SignInWithMicrosoft.tsx
- packages/app-builder/src/routes/_auth+/sign-in.tsx
- packages/app-builder/src/services/auth/auth.server.ts
- packages/app-builder/src/utils/hooks/use-async.ts
Small UI improvment: I realized the sign in page give no loading feedback. This is not a pain on local because the sign in promise is fast but on deployed env it's long enough to be weird.
I must admit I really ask myself why the app wasn't responding.
NB: it was longer than expected, mostly due to FB (= an async log in on the client with FB and an async log in on the server for Marble data)
> feat(sign-in): add loading spinner on sign in

- packages/app-builder/public/locales/en/settings.json
- packages/app-builder/src/components/Form/FormField.tsx
- packages/app-builder/src/components/HelpCenter.tsx
- packages/app-builder/src/routes/_builder+/settings+/webhooks.tsx
- packages/app-builder/src/routes/ressources+/settings+/webhooks+/create.tsx
- packages/app-builder/src/routes/ressources+/settings+/webhooks+/update.tsx
- packages/app-builder/src/services/chatlio/ChatlioWidget.tsx
- packages/app-builder/src/services/documentation-href.ts
In short :
Bonnus: 
- allow to open `HelpCenter` w\ Chalio config (usefull for on premise/open source users that do not configure it)
- allow to inject "component" (= formatted string with link mostly) in decsription form field
> feat(webhooks): add documentation for webhooks

- packages/app-builder/src/repositories/CaseRepository.ts
I suppose it was not caught by typescript because all the attributes to the update body are optional, and typescript is not designed to prevent additional properties from being passed in an object ?
Before merging (we'll do a hotfix release later today), could you please have a look if there may be other such cases introduced by your PR earlier this week on models & dtos @balzdur ?
> fix: regression in mapping to case update DTO

- packages/app-builder/src/repositories/LicenseRepository.ts
Should fix the issue described in [this Slack thread](https://checkmarble.slack.com/archives/C063SMVJ4BY/p1724062869469469)
Note: I realised we do not have consistency in the license used in dev between `api` and `app`, I propose a solution in [this backend PR](https://github.com/checkmarble/marble-backend/pull/650) but we can merge the frontend PR without the backend and it should fix the above issue
> chore: update dev license to disable webhooks in dev environment

- packages/app-builder/public/locales/en/upload.json
- packages/app-builder/src/routes/_builder+/upload+/$objectType.tsx
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/src/generated/marblecore-api.ts
Goes with https://github.com/checkmarble/marble-backend/pull/659
---
> correct display of upload log status

- packages/app-builder/src/components/Decisions/RulesDetail.tsx
Do not display the switch when no evaluation data is prevent (toggle a switch with no visual change feels buggy)
☝🏽 nothing happen when we toggle the switch
> DisplayReturnValuesSwitch only when rule has been evaluated

- packages/app-builder/src/components/Cases/CaseDecisions.tsx
- packages/app-builder/src/components/Decisions/RulesDetail.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilder.tsx
- packages/app-builder/src/models/custom-list.ts
- packages/app-builder/src/models/editable-ast-node.ts
- packages/app-builder/src/models/scenario-iteration-rule.ts
- packages/app-builder/src/models/scenario-iteration.ts
- packages/app-builder/src/models/scenario-publication.ts
- packages/app-builder/src/models/scenario.ts
- packages/app-builder/src/repositories/CustomListRepository.ts
- packages/app-builder/src/repositories/ScenarioRepository.ts
- packages/app-builder/src/repositories/init.server.ts
- packages/app-builder/src/routes/_builder+/cases+/$caseId.tsx
- packages/app-builder/src/routes/_builder+/decisions+/$decisionId.tsx
- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
- packages/app-builder/src/routes/_builder+/lists+/_index.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/decision.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/trigger.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/rules.$ruleId.tsx
- packages/app-builder/src/routes/ressources+/lists+/create.tsx
- packages/app-builder/src/routes/ressources+/lists+/delete.tsx
- packages/app-builder/src/routes/ressources+/lists+/edit.tsx
- packages/app-builder/src/routes/ressources+/lists+/value_create.tsx
- packages/app-builder/src/routes/ressources+/lists+/value_delete.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/deactivate.tsx
- packages/app-builder/src/services/ast-node/options.tsx
- packages/app-builder/src/services/auth/auth.server.ts
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/src/generated/marblecore-api.ts
Goes with https://github.com/checkmarble/marble-backend/pull/663: deprecate camel case fields of custom list dtos
- add custom list repository
- snake case dtos:
- custom lists
- scenario iteration rules
> custom list repository

- packages/app-builder/src/entry.client.tsx
- packages/app-builder/src/infra/firebase.ts
- packages/app-builder/src/services/auth/auth.client.ts
- packages/app-builder/src/services/init.client.ts
- packages/app-builder/src/services/init.server.ts
- packages/app-builder/src/utils/environment.ts
Refactor of the `environment` file in order to abstract away the "parsing" of some dependant environment variables (= here the Firebase config).
It should not introduce any breaking change since the expected env vars from the infra are still the same.
> refactor(env): better handling of firebase config

- Dockerfile
- Dockerfile_local
I tried to iterate locally, it seems to be working (at least, the server start and return an error since there is no backend etc...)
Let's see how it behaves on CI + staging
> chore(docker): try to use a distroless image

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AggregationEdit/EditDataModelField.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditor.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditorDiscoveryResults.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandMenuItem.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandInfos.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandLabel.tsx
- packages/ui-design-system/src/Menu/Menu.tsx
In short :
- enlarge the combobox popups
- better handling of long operand labels
**Some screenshots**
> feat(AstBuilder): handle long text in OperandEditor

- packages/app-builder/src/models/marble-session.ts
- packages/app-builder/src/repositories/SessionStorageRepositories/LngStorageRepository.ts
- packages/app-builder/src/repositories/SessionStorageRepositories/index.ts
- packages/app-builder/src/repositories/init.server.ts
- packages/app-builder/src/routes/ressources+/user+/language.tsx
- packages/app-builder/src/services/i18n/i18next.server.ts
- packages/app-builder/src/services/init.server.ts
Small refacto to store the `lng` preference in a separate cookie.
Before that, the `lng` pref was stored on the user session. On each logout, the user session is destroyed and thus the `lng` pref is lost, defaulting to the inferred lng from the browser.
> feat(i18n): improve lng persistence

- Dockerfile
- Dockerfile_local
- packages/app-builder/package.json
- pnpm-lock.yaml
I think I found the issue with the esbuild thing in Docker image
> chore(deps): move remix-flat-routes to devDependencies

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditor.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditorDiscoveryResults.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditorProvider.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditorSearchResults.tsx
In this PR:
- fix discovery result ordering
- refactor the comp so the discovery results is cached (= computed at first render)
- improve search logic with improved key generation logic (to prevent key colision)
> refactor(operand-editor): improve discovery results grouping

- .github/workflows/build_and_deploy.yaml
In this PR :
- inject sentry env vars (since they are not created anymore by the previous dedicated action)
- update some actions to resolve warnings from the CI (due to Node version updation in Github Actions)
> chore(ci): update google-github-actions to v2

- packages/app-builder/src/components/Decisions/TriggerObjectDetail.tsx
Improve `TriggerObjectDetail`:
- Handle long text with `break-all`
- cleaner UI using grid (ISO Figma) so it's clearer to read
**Before**
**After**
> fix(TriggerObjectDetail): handle long text in trigger object detail

- .github/workflows/build_and_deploy.yaml
- packages/app-builder/vite.config.ts
Last of the week and also (🤞🏽) last of all...
The sentry release name logic do not work for staging (I expect it to work for prod since we do use the tag, but I prefer to use an explicit easy to understand logic)
> fix(ci): update sentry release name

- packages/app-builder/src/components/Cases/CasesList.tsx
- packages/app-builder/src/components/Decisions/DecisionsList.tsx
Small changes on tables :
- simplify lists: when a row is "clickable", do not use links inside cells (to prevent having multiple navigations per rows)
- improve UI (reduce column sizes, use `line-clamp` when required...)
> feat: remove link inside tables

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/AstBuilderNode.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/MainAstLine.tsx
- packages/app-builder/src/locales/ar/scenarios.json
- packages/app-builder/src/locales/en/scenarios.json
- packages/app-builder/src/locales/fr/scenarios.json
- packages/app-builder/src/models/ast-node.ts
- packages/app-builder/src/models/editable-operators.ts
- packages/app-builder/src/services/editor/ast-editor.tsx
- packages/app-builder/src/services/editor/options.tsx
- packages/app-builder/src/services/validation/ast-node-validation.ts
- packages/app-builder/src/utils/array.ts
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/src/generated/marblecore-api.ts
Goes with PR https://github.com/checkmarble/marble-backend/pull/743 on the backend.
Implements the IsEmpty and IsNotEmpty operators, but only on the main AST (not for aggregator filters).
The operator returns true if the value is NULL or empty string, else false.
Starting from a binary operator
I can remove the right leg by setting the operator to "is empty"
and back again
it also works with nesting
Decision view display does basically what we can expect it to do
> WIP: isEmpty operator

- packages/app-builder/src/routes/ressources+/data+/createField.tsx
- packages/app-builder/src/routes/ressources+/data+/createLink.tsx
- packages/app-builder/src/routes/ressources+/data+/createTable.tsx
TBH I'm voluntarily not adding translations for the error message for now - I have a shitload of things to finish, and I'm keeping this for later maybe.
See also https://github.com/checkmarble/marble-backend/pull/752 for backend enforcing
> table,field,link name match ^[a-z]+[a-z0-9_]+

- packages/app-builder/src/routes/_builder+/_layout.tsx
- packages/app-builder/src/routes/app-router.tsx
Move the error component to handle Marble admin (and allow logout without clearing the cookies).
**Context:**
Historically, I added a special handler to handle Marble admin that try to log into the marble core app (ex: people that alternate between backoffice and marble app). Since this is not possible, the user is blocked on an error page, without the possibility to logout: he must clear auth cookies from the browser...
By adding TC, I added a `/app-router` responsible to redirect the user on the correct app. I forggot to move the error handler for Marble admin.
> refactor: lift up error boundary to app-router

- packages/app-builder/eslint.config.mjs
- packages/app-builder/src/locales/ar/lists.json
- packages/app-builder/src/locales/en/lists.json
- packages/app-builder/src/locales/fr/lists.json
- packages/app-builder/src/routes/_builder+/api.tsx
- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
- packages/app-builder/src/services/DownloadCaseFilesService.ts
- packages/app-builder/src/utils/download-file.ts
In this PR :
- download custom list values as CSV (single column list of values)
- upload custom list values as CSV (single column list of values)
- display usefull error messages (if any)
- display some ingestion statistics (if succeed)
> feat(custom-list): allow to manage list values as CSV

- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
- packages/app-builder/src/services/DownloadCaseFilesService.ts
- packages/app-builder/src/utils/download-file.ts
with https://github.com/checkmarble/marble-backend/pull/791
Download files for csv values of custom lists with proper encoding of file names (e.g. `"liste_de_critères.csv"` instead of `"liste de crit%C3%A8res.csv"`)
> properly encode file names for csv download

- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditModal/AggregationEdit/AggregationEdit.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandEditor/OperandEditModal/AggregationEdit/EditFilters.tsx
- packages/app-builder/src/components/Scenario/AstBuilder/AstBuilderNode/Operand/OperandInfos.tsx
- packages/app-builder/src/models/astNode/aggregation.ts
- packages/app-builder/src/models/modale-operators.ts
- packages/app-builder/src/models/operator-options.ts
Added:
- is empty, is not empty: which are unaries and work on any data type
- starts with, ends with: which only work on string data type
Backend PR: https://github.com/checkmarble/marble-backend/pull/801
> feat: add aggregation filter operators

- packages/app-builder/.env.example
- packages/app-builder/src/utils/environment.ts
Same rationale as the backend one.
Big difference, though: this actually changes some code to mark some variables as optional. I do not think we use them for anything, from what I can see in the code and the Firebase project, so having them in the configuration file might clutter it for nothing.
> Improve documentation of the env file example 

- packages/app-builder/src/models/marble-session.ts
- packages/app-builder/src/services/auth/auth.server.ts
Too much information was stored in auth session cookie, namely "user" and "entitlements" taking too much space in the cookie (which are limited to 4KB in size in total for a domain) nearing the maximum size they can take.
They were only used in the `isAuthenticated` auth service function.
What we did is remove `user` and `entitlements` from the cookie and instead of reading them from the cookie in the `isAuthenticated` auth service function, we now call the call the dedicated services.
> fix: remove user and entitlements from auth session cookie

- packages/app-builder/src/routes/_builder+/api.tsx
together with https://github.com/checkmarble/marble-backend/pull/835, fixes openapi spec generation
> fix openapi spec download

- packages/app-builder/src/components/Cases/CaseDecisions.tsx
- packages/app-builder/src/components/Decisions/SanctionCheckDetail.tsx
- packages/app-builder/src/components/Decisions/decisions-i18n.ts
- packages/app-builder/src/locales/ar/sanctions.json
- packages/app-builder/src/locales/en/sanctions.json
- packages/app-builder/src/locales/fr/sanctions.json
- packages/app-builder/src/routes/_builder+/cases+/$caseId_.sanctions.$decisionId+/_layout.tsx
- packages/app-builder/src/routes/ressources+/cases+/review-decision.tsx
- Add information from sanction check in decision detail
- Keep button to sanction check on case when it's reviewed, changed the wording accordingly
- Add back button before breadcrumb leading to case page on sanction pages
- Make the decision able to be approved only if the sanction check (if there's one) has the status "no_hit"
> fix: fix sanctions checks bugs

- packages/app-builder/src/components/Breadcrumbs.tsx
- packages/app-builder/src/components/Scenario/Sanction/FieldNode.tsx
- packages/app-builder/src/components/Scenario/Sanction/FieldNodeConcat.tsx
- packages/app-builder/src/components/Scenario/Sanction/FieldTrigger.tsx
- packages/app-builder/src/components/Scenario/Sanction/MatchOperand.tsx
- packages/app-builder/src/locales/ar/scenarios.json
- packages/app-builder/src/locales/en/scenarios.json
- packages/app-builder/src/locales/fr/scenarios.json
- packages/app-builder/src/models/sanction-check-config.ts
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_edit-view+/rules.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/_layout.tsx
- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/sanction.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/sanctions+/create.tsx
- packages/app-builder/src/routes/ressources+/scenarios+/$scenarioId+/$iterationId+/sanctions+/delete.tsx
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/src/generated/marblecore-api.ts
> Handling last remark for sanction check config

- packages/app-builder/src/components/ExternalLink.tsx
- packages/app-builder/src/constants/sanction-check-entity.tsx
Display wikidata ID as a link in sanction check match:
> feat: display wikidata Id as a link

- packages/app-builder/src/components/Sanctions/MatchDetails.tsx
Text was overflowing from its container:
Text is not overflowing anymore:
> fix: break all spaces on sanction check matches

- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/sanction-checks.yml
- packages/marble-api/src/generated/marblecore-api.ts
The backend adds a new API to instruct it to enrich a match payload with additional data not present in the initial search.
> OpenAPI: add the match enrichment API.

- packages/app-builder/src/locales/ar/scenarios.json
- packages/app-builder/src/locales/en/scenarios.json
- packages/app-builder/src/locales/fr/scenarios.json
- packages/app-builder/src/services/validation/scenario-validation-error-messages.ts
See https://github.com/checkmarble/marble-backend/pull/889 for error codes definition.
Display a "pretty" error message below the field selector in the aggregation modale when the state of the node is not completely set, or inconsistent choices are made.
No field chosen:
Field chosen has a type that is not compatible with this aggregation function:
> Better error messages in aggregation modale

- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/sanction.tsx
Fix casting of `lastData` as it can be undefined on first page load
> fix: LoM on sanction check page

- packages/app-builder/src/routes/_builder+/upload+/$objectType.tsx
This PR touches the error message displayed to the user when an issue happens with CSV parsing. We used to display the raw JSON returned by the backend, this parses the JSON to only display the message.
Do not hesitate to edit this PR if you want to improve either how it is displayed, or how I implemented it.
> Try and extract error message from ingestion error.

- packages/app-builder/src/models/license.ts
The frontends seemed to be using the `webhooks` entitlement for gating access to rule snoozing instead of the proper `rule_snoozes` entitlement.
> Fix rule snooze gating using webhook entitlement.

- packages/app-builder/src/locales/ar/settings.json
- packages/app-builder/src/locales/en/settings.json
- packages/app-builder/src/locales/fr/settings.json
See https://github.com/checkmarble/marble-backend/pull/929
> add warning on the webhooks UI: filtering by event type is restricted

- packages/app-builder/src/components/AstBuilder/edition/EditModal/Container.tsx
- packages/app-builder/src/components/AstBuilder/edition/EditModal/modals/TimeAdd/TimeAdd.tsx
- packages/app-builder/src/components/AstBuilder/edition/EditionNode.tsx
- Fix CSS issue on date edition modale when field content was too long:
- Make AST Builder modal not closable from outside click or escape key down (same as before the rework)
> fix: fix css issue ast builder date edition modal

- packages/app-builder/src/components/GithubBanner.tsx
- packages/app-builder/src/components/Page.tsx
Moving github banner in the left sidebar to be less intrusive for the user
> feat: move github banner in LeftSidebar

- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
Adds missing assignee attribute to case DTO.
Depends on https://github.com/checkmarble/marble-backend/pull/937 to be merged.
> Add case assignee to case DTO.

- packages/app-builder/src/routes/_builder+/lists+/$listId.tsx
This builds on #777.
After functional testing of the new params schema introduced there, we can now update the custom lists breadcrumb to use short UUIDs for consistency across pages.
> fix(custom-lists): use shortUUID in breadcrumb

- packages/app-builder/src/routes/ressources+/cases+/review-sanction-match.tsx
Checkboxes on firefox return "on"/"off" values instead of a boolean.
> fix: fix incorrect form checking on sanction check whitelisting

- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/_schemas.yml
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/openapis/marblecore-api/data-model.yml
- packages/marble-api/openapis/marblecore-api/ingestion.yml
- packages/marble-api/src/generated/marblecore-api.ts
Example call to client object listing endpoint
Call `POST https://api.checkmarble.com/client_data/transactions/list`
with body
```json
{
"exploration_options": {
"source_table_name": "accounts",
"filter_field_name": "account_id",
"filter_field_value": "00000000-0000-0000-0000-000000000000",
"ordering_field_name": "transaction_at"
},
"cursor_id": "c978368b-4e24-44da-b8cb-73d1950132c0",
"limit": 50
}
```
assuming we come from an object of type "accounts" with id `"00000000-0000-0000-0000-000000000000"` and we want to paginate after the transaction with object_id `"c978368b-4e24-44da-b8cb-73d1950132c0"` in the order of (transaction_at desc, object_id).
Assuming also a data model like
```json
{
"tables": {
"accounts": {
"name": "accounts",
"fields": {
"object_id": {
"data_type": "String", …
```
> Api spec for data exploration in case manager

- packages/app-builder/src/components/Cases/Events/SarCreated.tsx
- packages/app-builder/src/models/cases.ts
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/_schemas.yml
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/openapis/marblecore-api/data-model.yml
- packages/marble-api/src/generated/marblecore-api.ts
This PR contains two changes:
* Fix new case events OpenAPI specs to remove extra constraint and fields that were incorrectly set.
* Add specs for new data model table display options endpoints.
> Add data model table options specs + fix case event specs

- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
- packages/app-builder/src/routes/ressources+/cases+/escalate-case.tsx
- Use the `parseIdParamSafe` function to validate the inbox ID on the inbox page.
- After escalating a case, use the sUUID to navigate back to the originating inbox.
> fix(inbox): use sUUID to navigate back to inbox

- packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx
> fix: fix status tag on case history wrapping on two lines

- packages/app-builder/src/components/Tags/ColorSelect.tsx
> fix: fix color dropdown height on tag creation modal

- packages/app-builder/src/locales/ar/cases.json
- packages/app-builder/src/locales/en/cases.json
- packages/app-builder/src/locales/fr/cases.json
- packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx
- packages/app-builder/src/routes/ressources+/cases+/escalate-case.tsx
- packages/ui-design-system/src/Tooltip/Tooltip.tsx
- Disable the case escalation button when the current inbox does not have an escalation inbox configured.
- Display a tooltip when the button is disabled.
------------------------------------------------------
**1. For non admin users**
------------------------------------------------------
**2. For admins (with a link to the current inbox settings page) :**
------------------------------------------------------
**3. When the button is active :**
> fix(case-manager): Improve case escalation check

- packages/app-builder/src/components/Data/TableDetails.tsx
- parent field name was referenced instead of the related table
> fix: replace field name by table name in link section of data model #803

- packages/app-builder/src/components/Cases/CaseRightPanel.tsx
- packages/app-builder/src/locales/ar/cases.json
- packages/app-builder/src/locales/en/cases.json
- packages/app-builder/src/locales/fr/cases.json
- packages/app-builder/src/repositories/CaseRepository.ts
- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
- packages/app-builder/src/routes/_builder+/cases+/inboxes._layout.tsx
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
Appends a link to the case inboxes list to display all cases assigned to the user.
To avoid duplication and preserve the existing layout and logic of the inbox view, this new list is rendered as a standard inbox with an 'assigned-to-me' identifier. This allows us to fully reuse the existing logic. Only filters and navigation links are overridden as needed.
Feel free to challenge or suggest improvements to this approach.
> feat(cases-manager): Add a all-my-cases filtered inbox view

- packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanelContent.tsx
- packages/app-builder/src/components/Cases/CaseStatus.tsx
- packages/app-builder/src/models/cases.ts
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
Fix status case to:
- Have pending status in grey
- Have the outcome display when the case has one which is not "unset"
> fix: case status tag color and displayed status

- packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanel.tsx
- packages/app-builder/src/components/DataModelExplorer/DataModelExplorer.tsx
When closing last tab of data explorer we should shrink the drawer back to the pivot panel
> fix: should shrink drawer when closing last tab on data exploration

- packages/app-builder/src/hooks/useCursorPaginatedFetcher.ts
For some reason, the pagination state was not updating when navigating between inboxes on the /inbox pages.
Adding a cleanup function to the useEffect() in useCursorPaginatedFetcher—which resets the pagination state—resolved the issue.
> fix(pagination): add missing cleanup function in useEffect

- .vscode/settings.json
- Because eslint triggers an error and it's a pain to do it manually
> chore: add vscode workspace config to remove unused imports on save

- packages/app-builder/src/entry.server.tsx
- packages/app-builder/src/services/init.server.ts
- packages/app-builder/src/utils/environment.ts
**Warning:** This PR is a breaking change related to the deployment!
When in production mode, it checks the environment for any missing or invalid variables and refuses to start if it finds an issue. It is quite contrary to what currently happens where the server would always start properly, and error out during the requests.
This is one approach. There could be better ones if we find crashing out a bit excessive, for instance, we could fail the healthcheck (the server would still start in probeless environments).
@ChibiBlasphem Please roast this to do it TheRightWay ™️ .
> Fail early on invalid environment, default value for SESSION_MAX_AGE

- packages/app-builder/src/models/inbox.ts
- packages/app-builder/src/repositories/InboxRepository.ts
- packages/app-builder/src/routes/_builder+/_layout.tsx
- packages/app-builder/src/routes/_builder+/settings+/_index.tsx
- packages/app-builder/src/routes/_builder+/settings+/_layout.tsx
- packages/app-builder/src/routes/_builder+/settings+/inboxes.$inboxId.tsx
- packages/app-builder/src/routes/_builder+/settings+/inboxes._index.tsx
- packages/app-builder/src/routes/_builder+/settings+/scenarios.tsx
- packages/app-builder/src/routes/ressources+/settings+/inboxes+/update.tsx
- packages/app-builder/src/services/feature-access.ts
- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/_schemas.yml
- packages/marble-api/openapis/marblecore-api/inboxes.yml
- packages/marble-api/src/generated/marblecore-api.ts
The `Inboxes` tab of the setting was only accessible to organization admins, and any action within it as well. This PR makes it so the list can be accessed if the user is admin on at least one inbox, and so are all the actions offered by the feature.
This goes with checkmarble/marble-backend#988 that adds checks for update permissions.
> Make inbox settings accessible by inbox admins.

- packages/app-builder/src/components/Cases/CaseEvents.tsx
- packages/app-builder/src/components/Cases/Events/Filters/index.tsx
File uploads should be displayed along with comments by default, otherwise you have no visual hint that your file has actually been uploaded
> display comments AND file uploads by default

- packages/app-builder/src/routes/_builder+/settings+/inboxes._index.tsx
Hopefully, this is the last fix on inbox management. We need to filter out inboxes where the user is only a member, since there is no real value in showing them.
> Remove inbox settings from inbox members.

- .github/workflows/build_and_deploy.yaml
- .github/workflows/check.yaml
Fixes https://github.com/checkmarble/marble-frontend/security/code-scanning/15, following a similar fix on the backend
> restrict permissions on workflow to fix code scanning alert

- packages/app-builder/src/components/CaseManager/PivotsPanel/PivotsPanel.tsx
Pass a key attribute to the PivotsPanelContent component to force its state to reset when navigating from one case to another.
see https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes
> fix(case-manager): Reset component state

- packages/app-builder/src/components/Cases/Filters/CasesFiltersBar.tsx
- packages/app-builder/src/components/Cases/Filters/CasesFiltersContext.tsx
- packages/app-builder/src/components/Cases/Filters/FilterDetail/CasesExcludeAssignedFilter.tsx
- packages/app-builder/src/components/Cases/Filters/FilterDetail/CasesSnoozedFilter.tsx
- packages/app-builder/src/components/Cases/Filters/FilterDetail/ClosedCasesFilter.tsx
- packages/app-builder/src/components/Cases/Filters/FilterDetail/FilterDetail.tsx
- packages/app-builder/src/components/Cases/Filters/filters.ts
- packages/app-builder/src/components/Filters/SimpleFilter.tsx
- packages/app-builder/src/locales/ar/cases.json
- packages/app-builder/src/locales/en/cases.json
- packages/app-builder/src/locales/fr/cases.json
- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
🛠 Rework of the Inboxes Page Filters UI
Changes:
- Removed the first headline containing filter information and consolidated all filter-related UI into the second headline.
- The second headline is now always visible.
- Introduced a new SimpleFilter entity and component for filters that don’t require additional settings.
- When no filters are applied, a “Filters” button is shown on the left side of the filter bar.
When filters are active, a “New filter” button appears after the list of applied filters instead.
> feat(inboxes): rework filters

- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
Add a fallback statuses filter (all except “resolved”) when no filter is selected.
Currently, only the “resolved” (closed) filter is available.
With this change:
- If no status filter is applied, the list defaults to all cases except resolved.
- If the “resolved” filter is selected, only resolved cases are shown.
> fix(cases): filter out closed cases when no statuses are provided

- packages/app-builder/src/routes/_builder+/cases+/$caseId+/_index.tsx
The Case Manager page forces the main menu to fold on load to maximize space for case data.
Previously, this was done unconditionally, ignoring the user’s display preference stored in a cookie.
This caused inconsistent behavior—such as unexpected menu toggling—especially when the user refreshed the page.
With this change:
•	The menu is folded only if it was previously open.
•	This override is persisted in the cookie to maintain consistency across navigation and page refreshes.
•	If the menu was already folded, no changes are made.
> fix(menu): prevent unwanted main menu toggling behavior

- packages/app-builder/src/components/Sanctions/MatchCard.tsx
- packages/app-builder/src/routes/_builder+/decisions+/$decisionId.tsx
Display tags on two lines if needed.
**Before:**
**After:**
> feat: Improves layout and wrapping for match card content

- packages/app-builder/src/routes/_builder+/scenarios+/$scenarioId+/i+/$iterationId+/sanctions.$sanctionId.tsx
- packages/ui-design-system/src/MenuCommand/MenuCommand.tsx
- packages/ui-design-system/src/Modal/Modal.tsx
Fixes an issue introduced in PR #909  where the Modal’s z-index is too high, causing the MenuCommand selector to be rendered behind it.
This PR does :
- Revert the z-index changes on Modal component to prevent any regression on the UI.
- Decrease z-index on the sticky banner on sanction check rule CRUD page
---------------------------------------------------------------------------------------
refs: https://linear.app/marble-eu/issue/MAR-1092
> fix(screening): display sticky banner under popover elements on CRUD page

- packages/app-builder/src/components/Sanctions/SanctionReview.tsx
- packages/app-builder/src/models/sanction-check.ts
- packages/marble-api/openapis/marblecore-api/sanction-checks.yml
- packages/marble-api/src/generated/marblecore-api.ts
With trigger bail out from the sanction it is possible to have screenings with a status of "no_hit" but no request.
> fix(screening): allow no_hit screening to have no request

- packages/app-builder/src/components/Settings/UnavailableBanner.tsx
- packages/app-builder/src/locales/ar/settings.json
- packages/app-builder/src/locales/en/settings.json
- packages/app-builder/src/locales/fr/settings.json
add missing translation on unavailability banner :
> feat(case-auto-assignment): improve translations

- packages/app-builder/src/components/Decisions/AddToCase.tsx
- packages/app-builder/src/routes/ressources+/cases+/add-to-case.tsx
- Action (add to case) can redirect so `res` is possibly undefined
> fix(decisions): add to case reaching wrong result prop

- packages/app-builder/src/components/Navigation.tsx
- packages/app-builder/src/components/Nudge.tsx
- packages/app-builder/src/routes/_builder+/_layout.tsx
- packages/app-builder/src/routes/_builder+/settings+/_layout.tsx
- "nudge" button is invisible if the side bar is folded (which should increasingly be its default status)
- "webhooks" nudge button in setting was not handling all the cases where it should be displayed
- "upgrade" button link in the hover did not do anything on click, only on "ctrl+click"
- I tried to make the nudge a miniature when the side bar is folded. I managed to make something that feels about right on the initial render, but the icon shifts back over the analytics page logo on the client re-render. I wasn't able to fix this.
- on the webhooks setting page, the nudge logo flickers around when we refresh the page, if the webhooks setting page is selected
server render:
client render:
Some of the changes in this PR have been made with cursor, handle with care (especially the css)
> fix nudge display on settings/webhooks

- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/_schemas.yml
- packages/marble-api/openapis/marblecore-api/ai.yml
- packages/marble-api/src/generated/marblecore-api.ts
This pull request introduces a new set of API endpoints and schema definitions to support organization-level AI settings in the Marble API. The changes add the ability to get and update AI-related configuration via `/settings/ai`, and define the necessary data structures for these settings.
* Added the `/settings/ai` endpoint to the OpenAPI specification, enabling GET and PUT operations for organization AI settings. [[1]](diffhunk://#diff-963b87ef05c0ce68eb1bfe918763408aa2af4ae6a8dec97501fb911338484b8bR347-R351) [[2]](diffhunk://#diff-caad7b7de69bd6b95117468aaf81c86cc14aba5382343531d7d61b338f712d9dR1-R105)
* Defined new schemas in `ai.yml` for `KycEnrichmentSettingDto`, `CaseReviewSettingDto`, `AISettingsDto`, and `UpsertAISettingsDto`, specifying the structure of AI settings and their …
> feat(ai): add AI settings endpoint and related schemas to marblecore API

- packages/marble-api/openapis/marblecore-api.yaml
- packages/marble-api/openapis/marblecore-api/_schemas.yml
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
This pull request introduces a new API endpoint for enriching case data with KYC (Know Your Customer) analysis and adds supporting schema definitions to the Marble API. The main changes focus on extending the API to support KYC enrichment and providing the necessary data structures for the response.
* Added a new endpoint `/cases/{caseId}/enrich_kyc` to the API, allowing clients to enrich the pivot object of a case with KYC data if present. The endpoint returns an array of KYC analysis results. [[1]](diffhunk://#diff-963b87ef05c0ce68eb1bfe918763408aa2af4ae6a8dec97501fb911338484b8bR104-R105) [[2]](diffhunk://#diff-a8730fc82f48a0b94ce5f1c23c4b0d175b065f84a458089a07abea88e2c618f8R837-R868)
* Introduced the `KYCAnalysisDto` schema, which contains fields for the analysis output, entity name, …
> KYC enrichment in case

- .github/dependabot.yaml
Dependabot currently does not update the Bun lockfile in its bump PRs.
This PR enables enable-beta-ecosystems: true in the Dependabot configuration, which allows Bun lockfiles to be updated automatically.
Source: https://github.com/dependabot/dependabot-core/issues/6528#issuecomment-3001386217
> chore(dependabot): Enable beta ecosystems support

- packages/app-builder/src/components/Settings/IpWhitelisting/IpWhitelistingSettingsPage.tsx
- packages/app-builder/src/queries/settings/organization/update-allowed-networks.ts
- packages/app-builder/src/repositories/OrganizationRepository.ts
- packages/app-builder/src/routes/ressources+/settings+/organization+/$organizationId.update-allowed-networks.tsx
- packages/app-builder/src/utils/http/mutation.ts
- packages/marble-api/openapis/marblecore-api/admin.yml
- packages/marble-api/src/generated/marblecore-api.ts
This PR does 2 things:
- It updates the field with the registered ranges on the backend (they can be register différently than the values sent, i.e: "192.168.1.24" will become "192.168.1.24/32" and ranges are normalized)
- Allow single IP V4/V6 to be added instead of only ranges.
> feat: allow single IP in allow list MAR-1234

- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
This pull request introduces a new optional field to the case review API response to support pivot object enrichments. The main change is the addition of the `pivot_enrichments` property, which is designed to provide enrichment data for pivot objects when the feature is enabled.
**API schema enhancements:**
* Added a nullable `pivot_enrichments` field of type object to the case review response schema in `cases.yml`, including a `results` property that is an array of `KYCAnalysisDto` objects.
> feat: add enrichment result in case review DTO

- packages/app-builder/src/components/PaginationButtons.tsx
- packages/app-builder/src/hooks/useCursorPaginatedFetcher.ts
- packages/app-builder/src/locales/ar/cases.json
- packages/app-builder/src/locales/ar/common.json
- packages/app-builder/src/locales/en/cases.json
- packages/app-builder/src/locales/fr/cases.json
- packages/app-builder/src/repositories/CaseRepository.ts
- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
- Make default inbox pagination limit 50
- Add button to customize limit for 25, 50 and 100 items per page
> feat: set default inbox page size to 50 and make it customizable MAR-1245

- packages/app-builder/src/components/Cases/CasesList.tsx
- packages/app-builder/src/routes/_builder+/cases+/inboxes.$inboxId.tsx
- Page is now scrollable instead of the content of the table itself
- Make pagination bar sticky to the bottom
> feat(inboxes): make table take all the space and pagination sticky

- packages/app-builder/src/components/Cases/RequiredActions.tsx
- packages/app-builder/src/models/cases.ts
- packages/marble-api/openapis/marblecore-api/cases.yml
- packages/marble-api/src/generated/marblecore-api.ts
Fix: in this PR https://github.com/checkmarble/marble-backend/pull/1202
the "list decisions by case" endpoint now returns screenings (partial) in the decisions object, but it was not using the correct key.
More complete renaming of any remaining "sanctionCheck"s to be done in a later PR.
> fix: case manager page screenings key
